version: "3"

services:
  mariadb:
    container_name: blog_mariadb
    build:
      context: ./mariadb
      dockerfile: Dockerfile
    volumes:
      - ./volumes/mariadb_data:/var/lib/mysql
    #restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command: --character-set-server=utf8 --collation-server=utf8_general_ci

  php:
    container_name: blog_php
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./volumes/log/:/var/log/
      - ./aegea:/var/www/blog
    #restart: unless-stopped
    depends_on:
      - mariadb

  nginx:
    container_name: blog_nginx
    #restart: unless-stopped
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - mariadb
      - php
    volumes:
      - ./volumes/log/nginx:/var/log/nginx
      - ./aegea:/var/www/blog
      - ./index:/var/www/index
    ports:
      - 80:${NGINX_PORT}
    environment:
      NGINX_HOST: ${NGINX_HOST}
      NGINX_PORT: ${NGINX_PORT}
